version: "3.8"
services:
  api:
    build: ./api/
    container_name: api
    ports:
      - "4000:4000"
    command: npm start
    environment:
      MONGO_URI: mongodb://root:root@db:27017
      JWT_SECRET: ecommerce
    volumes:
      - "./api/:/app"
      - "/app/node_modules"
    image: mejbri1998/api:latest  

  client:
    build: ./client/
    container_name: client
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      REACT_APP_API_URL: http://api:4000
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    image: mejbri1998/client:latest  
  
  db:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
